import { PDFDocument, StandardFonts, type PDFPage, type PDFFont } from 'pdf-lib';
import type { Cue } from 'showx-shared';
import { visibleCues } from '../views/departmentFilter.js';
import { summarizePayload } from '../catalog/summarize.js';
import {
  PAGE_W, PAGE_H, MARGIN,
  FONT_SIZE_BODY, FONT_SIZE_SMALL, FONT_SIZE_TINY,
  FONT_SIZE_COVER_TITLE, FONT_SIZE_COVER_VENUE, FONT_SIZE_COVER_DEPT,
  ROW_HEIGHT, ROW_SECONDARY_OFFSET,
  COLOR_BLACK, COLOR_GREY,
  SM_COL_LABEL, SM_COL_DEPT, SM_COL_TRIGGER, SM_COL_STANDBY,
  OP_COL_LABEL, OP_COL_PAYLOAD, OP_COL_STANDBY,
  DEPT_CHIP_WIDTH, DEPT_CHIP_HEIGHT, DEPT_CHIP_COLORS,
} from './pdfStyles.js';

interface Fonts {
  regular: PDFFont;
  bold: PDFFont;
  mono: PDFFont;
}

type ShowMeta = { title?: string; venue?: string; date?: string };

// ── Helpers ───────────────────────────────────────────────────────────────────

function triggerBadge(cue: Cue): string {
  const t = cue.trigger;
  switch (t.kind) {
    case 'manual': return 'M';
    case 'auto_follow': return '→';   // →  (ASCII-safe in Helvetica)
    case 'auto_continue': return 'CONT';  // ⏩ outside Latin-1 — use ASCII fallback
    case 'timecode': return 'TC';         // ⏱ outside Latin-1 — use ASCII fallback
    default: return '?';
  }
}

function safeText(s: string, maxLen = 60): string {
  // Strip non-latin1 characters (pdf-lib StandardFonts are Latin-1 encoded).
  // eslint-disable-next-line no-control-regex
  return s.replace(/[^\x00-\xFF]/g, '?').substring(0, maxLen);
}

function lxPayloadSummary(cue: Cue): string {
  const p = cue.payloads.find((x) => x.type === 'lx_ref');
  if (!p || p.type !== 'lx_ref') return '—';
  return `Cue ${p.cue_list}/${p.cue_number}`;
}

function sxPayloadSummary(cue: Cue): string {
  const p = cue.payloads.find(
    (x) => x.type === 'osc' && /sound|sfx|audio|cue/i.test(x.address),
  );
  if (!p || p.type !== 'osc') return '—';
  return safeText(p.address, 50);
}

function videoPayloadSummary(cue: Cue): string {
  const p = cue.payloads.find((x) => x.type === 'osc');
  if (!p || p.type !== 'osc') return '—';
  const seg = p.address.split('/').pop() ?? p.address;
  return safeText(seg, 50);
}

function genericPayloadSummary(cue: Cue): string {
  return safeText(cue.payloads.map(summarizePayload).join('; '), 80);
}

function payloadSummaryForDept(cue: Cue, dept: string): string {
  switch (dept) {
    case 'LX': return lxPayloadSummary(cue);
    case 'SX': return sxPayloadSummary(cue);
    case 'VIDEO': return videoPayloadSummary(cue);
    default: return genericPayloadSummary(cue);
  }
}

// ── Cover page ────────────────────────────────────────────────────────────────

async function renderCoverPage(
  pdf: PDFDocument,
  fonts: Fonts,
  meta: ShowMeta,
  dept: string,
  subtitle: string,
): Promise<void> {
  const page = pdf.addPage([PAGE_W, PAGE_H]);
  const cy = PAGE_H / 2;

  page.drawText(safeText(meta.title ?? '(untitled show)', 60), {
    x: MARGIN, y: cy + 60, font: fonts.bold, size: FONT_SIZE_COVER_TITLE, color: COLOR_BLACK,
  });
  page.drawText(safeText(`${meta.venue ?? ''} · ${meta.date ?? ''}`, 80), {
    x: MARGIN, y: cy + 20, font: fonts.regular, size: FONT_SIZE_COVER_VENUE, color: COLOR_BLACK,
  });
  page.drawText(safeText(`${dept} cue sheet · ${subtitle}`, 60), {
    x: MARGIN, y: cy - 20, font: fonts.bold, size: FONT_SIZE_COVER_DEPT, color: COLOR_BLACK,
  });
  page.drawText(`Generated by ShowX 0.1 — ${new Date().toISOString()}`, {
    x: MARGIN, y: MARGIN, font: fonts.regular, size: FONT_SIZE_TINY, color: COLOR_GREY,
  });
}

// ── Page header / footer ──────────────────────────────────────────────────────

function renderPageHeader(page: PDFPage, font: PDFFont, meta: ShowMeta, dept: string, pageNum: number, totalPages: number): void {
  const title = safeText(`${meta.title ?? ''} — ${dept}`, 60);
  page.drawText(title, { x: MARGIN, y: PAGE_H - MARGIN + 5, font, size: FONT_SIZE_TINY, color: COLOR_BLACK });
  const pageStr = `Page ${pageNum} of ${totalPages}`;
  page.drawText(pageStr, {
    x: PAGE_W - MARGIN - font.widthOfTextAtSize(pageStr, FONT_SIZE_TINY),
    y: PAGE_H - MARGIN + 5,
    font, size: FONT_SIZE_TINY, color: COLOR_BLACK,
  });
}

function renderPageFooter(page: PDFPage, font: PDFFont, exportedAt: string): void {
  page.drawText(`ShowX 0.1 export · ${exportedAt}`, {
    x: MARGIN, y: MARGIN - 15, font, size: FONT_SIZE_TINY, color: COLOR_GREY,
  });
}

// ── Dept chip stripes (compound cue indicator) ────────────────────────────────

function renderDeptChips(page: PDFPage, cue: Cue, y: number): void {
  if (cue.department.length <= 1) return;
  let cx = MARGIN - DEPT_CHIP_WIDTH - 2;
  for (const dept of cue.department) {
    const color = DEPT_CHIP_COLORS[dept] ?? COLOR_GREY;
    page.drawRectangle({ x: cx, y: y - DEPT_CHIP_HEIGHT / 2, width: DEPT_CHIP_WIDTH, height: DEPT_CHIP_HEIGHT, color });
    cx -= DEPT_CHIP_WIDTH + 1;
    if (cx < 2) break;
  }
}

// ── SM Master render ──────────────────────────────────────────────────────────

export async function renderSmMasterPdf(meta: ShowMeta, cues: Cue[], cuelistName: string): Promise<PDFDocument> {
  const pdf = await PDFDocument.create();
  const [regular, bold, mono] = await Promise.all([
    pdf.embedFont(StandardFonts.Helvetica),
    pdf.embedFont(StandardFonts.HelveticaBold),
    pdf.embedFont(StandardFonts.Courier),
  ]);
  const fonts: Fonts = { regular, bold, mono };
  const exportedAt = new Date().toISOString();

  await renderCoverPage(pdf, fonts, meta, 'SM Master', cuelistName);

  if (cues.length === 0) {
    // No cues — cover page only. Update header/footer after page count known.
    renderPageHeader(pdf.getPage(0), bold, meta, 'SM Master', 1, 1);
    renderPageFooter(pdf.getPage(0), regular, exportedAt);
    return pdf;
  }

  const bodyPageStart = pdf.getPageCount();
  const bodyPages: PDFPage[] = [];
  let page = pdf.addPage([PAGE_W, PAGE_H]);
  bodyPages.push(page);
  let y = PAGE_H - MARGIN - 30;

  for (const cue of cues) {
    if (y < MARGIN + 30) {
      page = pdf.addPage([PAGE_W, PAGE_H]);
      bodyPages.push(page);
      y = PAGE_H - MARGIN - 30;
    }

    const col = COLOR_BLACK;
    renderDeptChips(page, cue, y);

    page.drawText(safeText(cue.label, 30), { x: SM_COL_LABEL, y, font: bold, size: FONT_SIZE_BODY, color: col });
    page.drawText(safeText(cue.department.join(','), 20), { x: SM_COL_DEPT, y, font: regular, size: FONT_SIZE_SMALL, color: col });
    page.drawText(safeText(triggerBadge(cue), 6), { x: SM_COL_TRIGGER, y, font: mono, size: FONT_SIZE_SMALL, color: col });
    page.drawText(safeText(cue.standby_note ?? '', 40), { x: SM_COL_STANDBY, y, font: regular, size: FONT_SIZE_SMALL, color: col });

    if (cue.description) {
      page.drawText(safeText(cue.description, 80), {
        x: SM_COL_LABEL, y: y - ROW_SECONDARY_OFFSET, font: regular, size: FONT_SIZE_SMALL - 1, color: COLOR_GREY,
      });
    }

    y -= ROW_HEIGHT;
  }

  // Apply header + footer to body pages now that total page count is known
  const totalPages = pdf.getPageCount();
  for (let i = bodyPageStart; i < totalPages; i++) {
    const p = pdf.getPage(i);
    renderPageHeader(p, bold, meta, 'SM Master', i - bodyPageStart + 1, totalPages - bodyPageStart);
    renderPageFooter(p, regular, exportedAt);
  }

  return pdf;
}

// ── Operator PDF render ───────────────────────────────────────────────────────

export async function renderOperatorPdf(
  meta: ShowMeta,
  allCues: Cue[],
  dept: string,
): Promise<PDFDocument> {
  const pdf = await PDFDocument.create();
  const [regular, bold, mono] = await Promise.all([
    pdf.embedFont(StandardFonts.Helvetica),
    pdf.embedFont(StandardFonts.HelveticaBold),
    pdf.embedFont(StandardFonts.Courier),
  ]);
  const fonts: Fonts = { regular, bold, mono };
  const exportedAt = new Date().toISOString();

  await renderCoverPage(pdf, fonts, meta, dept, 'Operator view');

  const filtered = visibleCues(allCues, {
    owned: new Set([dept]),
    watched: new Set(['SM']),
  });

  if (filtered.length === 0) {
    renderPageHeader(pdf.getPage(0), bold, meta, dept, 1, 1);
    renderPageFooter(pdf.getPage(0), regular, exportedAt);
    return pdf;
  }

  const bodyPageStart = pdf.getPageCount();
  const bodyPages: PDFPage[] = [];
  let page = pdf.addPage([PAGE_W, PAGE_H]);
  bodyPages.push(page);
  let y = PAGE_H - MARGIN - 30;

  for (const cue of filtered) {
    if (y < MARGIN + 30) {
      page = pdf.addPage([PAGE_W, PAGE_H]);
      bodyPages.push(page);
      y = PAGE_H - MARGIN - 30;
    }

    const isOwned = cue.department.includes(dept as any);
    const col = isOwned ? COLOR_BLACK : COLOR_GREY;

    renderDeptChips(page, cue, y);

    page.drawText(safeText(cue.label, 30), { x: OP_COL_LABEL, y, font: isOwned ? bold : regular, size: FONT_SIZE_BODY, color: col });
    page.drawText(safeText(payloadSummaryForDept(cue, dept), 50), {
      x: OP_COL_PAYLOAD, y, font: mono, size: FONT_SIZE_SMALL, color: col,
    });
    page.drawText(safeText(cue.standby_note ?? '', 40), { x: OP_COL_STANDBY, y, font: regular, size: FONT_SIZE_SMALL, color: col });

    if (cue.description) {
      page.drawText(safeText(cue.description, 80), {
        x: OP_COL_LABEL, y: y - ROW_SECONDARY_OFFSET, font: regular, size: FONT_SIZE_SMALL - 1, color: col,
      });
    }

    y -= ROW_HEIGHT;
  }

  const totalPages = pdf.getPageCount();
  for (let i = bodyPageStart; i < totalPages; i++) {
    const p = pdf.getPage(i);
    renderPageHeader(p, bold, meta, dept, i - bodyPageStart + 1, totalPages - bodyPageStart);
    renderPageFooter(p, regular, exportedAt);
  }

  return pdf;
}
