// src/shared/src/types/caller.ts
// Caller-line data model for the AI Showcaller feature (F4).

/**
 * Per-cue caller script: standby call per department + a single GO call.
 * standby is a sparse dict — departments not present = no standby for that dept.
 * aggregate is an optional pre-computed summary of all standby lines (for LLM draft).
 */
export interface CallerLineGroup {
  /** Sparse mapping from department tag to standby text. Absent key = no standby for that dept. */
  standby: { [dept: string]: string };
  /** GO call text spoken when cue fires. */
  go: string;
  /** Optional pre-aggregated summary (generated by B007-002/003). */
  aggregate?: string | null;
}
